Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2510
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2561
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2561
Not Found: /api/docs
"GET /api/docs HTTP/1.1" 404 2770
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2561
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2561
Not Found: /api/docs
"GET /api/docs HTTP/1.1" 404 2770
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2561
Not Found: /docs
"GET /docs HTTP/1.1" 404 2540
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2561
Not Found: /api/docs
"GET /api/docs HTTP/1.1" 404 2770
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2561
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4181
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2561
"GET /static/admin/css/base.css HTTP/1.1" 200 21207
"GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2929
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2694
"GET /static/admin/css/responsive.css HTTP/1.1" 200 18533
"GET /static/admin/css/login.css HTTP/1.1" 200 958
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
"GET /static/admin/js/theme.js HTTP/1.1" 200 1943
Not Found: /
"GET / HTTP/1.1" 404 2510
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2561
"GET /api/ HTTP/1.1" 200 595
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2561
Not Found: /docs/
"GET /docs/ HTTP/1.1" 404 2543
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2561
Not Found: /users/
"GET /users/ HTTP/1.1" 404 3398
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2561
Watching for file changes with StatReloader
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4181
"GET /static/admin/css/base.css HTTP/1.1" 200 21207
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2694
"GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2929
"GET /static/admin/js/theme.js HTTP/1.1" 200 1943
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
"GET /static/admin/css/responsive.css HTTP/1.1" 200 18533
"GET /static/admin/css/login.css HTTP/1.1" 200 958
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2561
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 6240
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2561
"GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
"GET /admin/auth/user/ HTTP/1.1" 200 11034
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2561
"GET /static/admin/css/changelists.css HTTP/1.1" 200 6566
"GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
"GET /static/admin/js/core.js HTTP/1.1" 200 5682
"GET /static/admin/js/actions.js HTTP/1.1" 200 7872
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 8943
"GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
"GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 292458
"GET /static/admin/img/search.svg HTTP/1.1" 200 458
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
"GET /static/admin/js/filters.js HTTP/1.1" 200 978
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
"GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
Internal Server Error: /admin/users/profile/
Traceback (most recent call last):
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedColumn: column profiles.user_timezone does not exist
LINE 1: ..._url", "profiles"."theme", "profiles"."language", "profiles"...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\contrib\admin\options.py", line 2065, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: column profiles.user_timezone does not exist
LINE 1: ..._url", "profiles"."theme", "profiles"."language", "profiles"...
                                                             ^

"GET /admin/users/profile/ HTTP/1.1" 500 167827
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2561
C:\Users\aliba\Documents\Hesabu\pefoma_backend\users\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\aliba\Documents\Hesabu\pefoma_backend\users\models.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\aliba\Documents\Hesabu\pefoma_backend\users\models.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /admin/users/profile/
Traceback (most recent call last):
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 187, in _get_session
    return self._session_cache
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\db\backends\base\base.py", line 289, in ensure_connection
    self.connect()
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\db\backends\base\base.py", line 270, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\db\backends\postgresql\base.py", line 275, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "aws-1-eu-north-1.pooler.supabase.com" (51.21.18.29), port 5432 failed: Connection timed out (0x0000274C/10060)
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "aws-1-eu-north-1.pooler.supabase.com" (13.60.102.132), port 5432 failed: Connection timed out (0x0000274C/10060)
	Is the server running on that host and accepting TCP/IP connections?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\contrib\admin\options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\contrib\admin\sites.py", line 230, in inner
    if not self.has_permission(request):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\contrib\admin\sites.py", line 203, in has_permission
    return request.user.is_active and request.user.is_staff
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\utils\functional.py", line 266, in inner
    self._setup()
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\utils\functional.py", line 419, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\contrib\auth\middleware.py", line 25, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\contrib\auth\middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\contrib\auth\__init__.py", line 191, in get_user
    user_id = _get_user_session_key(request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\contrib\auth\__init__.py", line 60, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 53, in __getitem__
    return self._session[key]
           ^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 192, in _get_session
    self._session_cache = self.load()
                          ^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 42, in load
    s = self._get_session_from_db()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 32, in _get_session_from_db
    return self.model.objects.get(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1560, in execute_sql
    cursor = self.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\db\backends\base\base.py", line 330, in cursor
    return self._cursor()
           ^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\db\backends\base\base.py", line 306, in _cursor
    self.ensure_connection()
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\db\backends\base\base.py", line 288, in ensure_connection
    with self.wrap_database_errors:
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\db\backends\base\base.py", line 289, in ensure_connection
    self.connect()
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\db\backends\base\base.py", line 270, in connect
    self.connection = self.get_new_connection(conn_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\django\db\backends\postgresql\base.py", line 275, in get_new_connection
    connection = self.Database.connect(**conn_params)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\aliba\Documents\Hesabu\pefoma_backend\.venv\Lib\site-packages\psycopg2\__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: connection to server at "aws-1-eu-north-1.pooler.supabase.com" (51.21.18.29), port 5432 failed: Connection timed out (0x0000274C/10060)
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "aws-1-eu-north-1.pooler.supabase.com" (13.60.102.132), port 5432 failed: Connection timed out (0x0000274C/10060)
	Is the server running on that host and accepting TCP/IP connections?

"GET /admin/users/profile/ HTTP/1.1" 500 246863
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2561
"GET /admin/ HTTP/1.1" 200 6240
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2561
"GET /admin/auth/group/ HTTP/1.1" 200 7805
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2561
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /admin/auth/group/add/ HTTP/1.1" 200 11301
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2561
"GET /static/admin/css/forms.css HTTP/1.1" 200 9047
"GET /static/admin/js/SelectBox.js HTTP/1.1" 200 4530
"GET /static/admin/css/widgets.css HTTP/1.1" 200 11900
"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
"GET /static/admin/js/SelectFilter2.js HTTP/1.1" 200 15292
"GET /static/admin/js/change_form.js HTTP/1.1" 200 606
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /static/admin/img/icon-unknown-alt.svg HTTP/1.1" 200 655
"GET /static/admin/img/selector-icons.svg HTTP/1.1" 200 3291
"GET /static/admin/img/icon-unknown.svg HTTP/1.1" 200 655
"GET /admin/users/profile/ HTTP/1.1" 200 11783
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2561
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /admin/users/profile/add/ HTTP/1.1" 200 24671
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2561
"GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19319
"GET /static/admin/js/calendar.js HTTP/1.1" 200 8466
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
"GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
"GET /admin/users/profile/ HTTP/1.1" 200 11783
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2561
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
Watching for file changes with StatReloader
"GET /swagger HTTP/1.1" 301 0
"GET /swagger/ HTTP/1.1" 200 2209
"GET /static/drf-yasg/style.css HTTP/1.1" 200 1047
"GET /static/drf-yasg/swagger-ui-init.js HTTP/1.1" 200 15480
"GET /static/drf-yasg/swagger-ui-dist/swagger-ui.css HTTP/1.1" 200 145206
"GET /static/drf-yasg/insQ.min.js HTTP/1.1" 200 2093
"GET /static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js HTTP/1.1" 200 1046583
"GET /static/drf-yasg/immutable.min.js HTTP/1.1" 200 56904
"GET /static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js HTTP/1.1" 200 322863
"GET /swagger/?format=openapi HTTP/1.1" 200 7097
"GET /static/drf-yasg/swagger-ui-dist/favicon-32x32.png HTTP/1.1" 200 628
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2982
"GET /static/drf-yasg/swagger-ui-dist/favicon-32x32.png HTTP/1.1" 200 628
"GET /static/drf-yasg/swagger-ui-dist/favicon-32x32.png HTTP/1.1" 200 628
"GET /static/drf-yasg/swagger-ui-dist/favicon-32x32.png HTTP/1.1" 200 628
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2982
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2982
Unauthorized: /api/v1/test/
"GET /api/v1/test/ HTTP/1.1" 401 58
Unauthorized: /api/v1/test/
"GET /api/v1/test/ HTTP/1.1" 401 58
"GET /api/ HTTP/1.1" 200 595
Service Unavailable: /api/v1/auth/health/
"GET /api/v1/auth/health/ HTTP/1.1" 503 285
Service Unavailable: /api/v1/auth/health/
"GET /api/v1/auth/health/ HTTP/1.1" 503 285
Service Unavailable: /auth/health/
"GET /auth/health/ HTTP/1.1" 503 285
C:\Users\aliba\Documents\Hesabu\pefoma_backend\pefoma_backend\settings.py changed, reloading.
Watching for file changes with StatReloader
Service Unavailable: /auth/health/
"GET /auth/health/ HTTP/1.1" 503 285
Service Unavailable: /auth/health/
"GET /auth/health/ HTTP/1.1" 503 285
Service Unavailable: /auth/health/
"GET /auth/health/ HTTP/1.1" 503 285
"GET /swagger/ HTTP/1.1" 200 2209
"GET /static/drf-yasg/style.css HTTP/1.1" 304 0
"GET /static/drf-yasg/swagger-ui-dist/swagger-ui.css HTTP/1.1" 304 0
"GET /static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js HTTP/1.1" 304 0
"GET /static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js HTTP/1.1" 304 0
"GET /static/drf-yasg/immutable.min.js HTTP/1.1" 304 0
"GET /static/drf-yasg/insQ.min.js HTTP/1.1" 304 0
"GET /static/drf-yasg/swagger-ui-init.js HTTP/1.1" 304 0
"GET /swagger/?format=openapi HTTP/1.1" 200 7097
"GET /static/drf-yasg/swagger-ui-dist/favicon-32x32.png HTTP/1.1" 304 0
Not Found: /favicon.ico
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2982
"GET /favicon.ico HTTP/1.1" 404 2982
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2982
Service Unavailable: /auth/health/
"GET /auth/health/ HTTP/1.1" 503 285
Watching for file changes with StatReloader
"GET /swagger/ HTTP/1.1" 200 2209
"GET /static/drf-yasg/style.css HTTP/1.1" 304 0
"GET /static/drf-yasg/swagger-ui-dist/swagger-ui.css HTTP/1.1" 304 0
"GET /static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js HTTP/1.1" 304 0
"GET /static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js HTTP/1.1" 304 0
"GET /static/drf-yasg/insQ.min.js HTTP/1.1" 304 0
"GET /static/drf-yasg/immutable.min.js HTTP/1.1" 304 0
"GET /static/drf-yasg/swagger-ui-init.js HTTP/1.1" 304 0
"GET /swagger/?format=openapi HTTP/1.1" 200 7097
"GET /static/drf-yasg/swagger-ui-dist/favicon-32x32.png HTTP/1.1" 304 0
Not Found: /favicon.ico
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2982
"GET /favicon.ico HTTP/1.1" 404 2982
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2982
Service Unavailable: /auth/health/
"GET /auth/health/ HTTP/1.1" 503 285
Watching for file changes with StatReloader
"GET /swagger/ HTTP/1.1" 200 2209
"GET /static/drf-yasg/style.css HTTP/1.1" 304 0
"GET /static/drf-yasg/swagger-ui-dist/swagger-ui.css HTTP/1.1" 304 0
"GET /static/drf-yasg/swagger-ui-dist/swagger-ui-bundle.js HTTP/1.1" 304 0
"GET /static/drf-yasg/swagger-ui-dist/swagger-ui-standalone-preset.js HTTP/1.1" 304 0
"GET /static/drf-yasg/insQ.min.js HTTP/1.1" 304 0
"GET /static/drf-yasg/immutable.min.js HTTP/1.1" 304 0
"GET /static/drf-yasg/swagger-ui-init.js HTTP/1.1" 304 0
"GET /swagger/?format=openapi HTTP/1.1" 200 7097
"GET /static/drf-yasg/swagger-ui-dist/favicon-32x32.png HTTP/1.1" 304 0
Not Found: /favicon.ico
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2982
"GET /favicon.ico HTTP/1.1" 404 2982
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2982
Service Unavailable: /auth/health/
"GET /auth/health/ HTTP/1.1" 503 250
Watching for file changes with StatReloader
"GET /swagger/ HTTP/1.1" 200 2209
"GET /swagger/?format=openapi HTTP/1.1" 200 7097
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2982
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2982
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2982
"GET /auth/health/ HTTP/1.1" 200 162
Bad Request: /auth/signup/
"POST /auth/signup/ HTTP/1.1" 400 404
"GET /admin/ HTTP/1.1" 200 6240
Not Found: /favicon.ico
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2982
"GET /favicon.ico HTTP/1.1" 404 2982
"GET /admin/auth/user/ HTTP/1.1" 200 11034
Not Found: /favicon.ico
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 2982
"GET /favicon.ico HTTP/1.1" 404 2982
"GET /admin/jsi18n/ HTTP/1.1" 200 3343
"GET /health/ HTTP/1.1" 200 70
HTTP Request: POST https://jgifsfiyhkackzkjsnsq.supabase.co/auth/v1/signup "HTTP/1.1 200 OK"
Successfully created user: alibalogun996@gmail.com
Created profile for user 921f22e0-b5e1-4311-a991-c10d3337e821
"POST /auth/signup/ HTTP/1.1" 201 234
